package pl.nbp.model.Enum;

public enum      CurrencyTypeInTableB {
    AFN("afgani (Afganistan)"),
    MGA("ariary (Madagaskar)"),
    PAB("balboa (Panama)"),
    ETB("birr etiopski"),
    VEF("bolivar (Wenezuela)"),
    BOB("boliwiano (Boliwia)"),
    CRC("colon kostarykański"),
    SVC("colon salwadorski"),
    NIO("cordoba oro (Nikaragua)"),
    GMD("dalasi (Gambia)"),
    MKD("denar (Macedonia)"),
    DZD("dinar algierski"),
    BHD("dinar bahrajski"),
    IQD("dinar iracki"),
    JOD("dinar jordański"),
    KWD("dinar kuwejcki"),
    LYD("dinar libijski"),
    RSD("dinar serbski"),
    TND("dinar tunezyjski"),
    MAD("dirham marokański"),
    AED("dirham ZEA (Zjednoczone Emiraty Arabskie)"),
    STN("dobra (Wyspy Świetego Tomasza i Książęca)"),
    BSD("dolar bahamski"),
    BBD("dolar barbadoski"),
    BZD("dolar belizeński"),
    BND("dolar brunejski"),
    FJD("dolar Fidżi"),
    GYD("dolar gujański"),
    JMD("dolar jamajski"),
    LRD("dolar liberyjski"),
    NAD("dolar namibijski"),
    SRD("dolar surinamski"),
    TTD("dolar Trynidadu i Tobago"),
    XCD("dolar wschodniokaraibski"),
    SBD("dolar Wysp Salomona"),
    VND("dong (Wietnam)"),
    AMD("dram (Armenia)"),
    CVE("escudo Republiki Zielonego Przylądka"),
    AWG("florin arubański"),
    BIF("frank burundyjski"),
    XOF("frank CFA BCEAO"),
    XAF("frank CFA BEAC"),
    XPF("frank CFP"),
    DJF("frank Dżibuti"),
    GNF("frank gwinejski"),
    KMF("frank Komorów"),
    CDF("frank kongijski (Dem. Republika Konga)"),
    RWF("frank rwandyjski"),
    EGP("funt egipski"),
    GIP("funt gibraltarski"),
    LBP("funt libański"),
    SSP("funt południowosudański"),
    SDG("funt sudański"),
    SYP("funt syryjski"),
    GHS("Ghana cedi"),
    HTG("gourde (Haiti)"),
    PYG("guarani (Paragwaj)"),
    ANG("gulden Antyli Holenderskich"),
    PGK("kina (Papua-Nowa Gwinea)"),
    LAK("kip (Laos)"),
    MWK("kwacha malawijska"),
    ZMW("kwacha zambijska"),
    AOA("kwanza (Angola)"),
    MMK("kyat (Myanmar, Birma)"),
    GEL("lari (Gruzja)"),
    MDL("lej Mołdawii"),
    ALL("lek (Albania)"),
    HNL("lempira (Honduras)"),
    SLL("leone (Sierra Leone)"),
    SZL("lilangeni (Suazi)"),
    LSL("loti (Lesotho)"),
    AZN("manat azerbejdżański"),
    MZN("metical (Mozambik)"),
    NGN("naira (Nigeria)"),
    ERN("nakfa (Erytrea)"),
    TWD("nowy dolar tajwański"),
    TMT("nowy manat (Turkmenistan)"),
    MRU("ouguiya (Mauretania)"),
    TOP("pa'anga (Tonga)"),
    MOP("pataca (Makau)"),
    ARS("peso argentyńskie"),
    DOP("peso dominikańskie"),
    COP("peso kolumbijskie"),
    CUP("peso kubańskie"),
    UYU("peso urugwajskie"),
    BWP("pula (Botswana)"),
    GTQ("quetzal (Gwatemala"),
    IRR("rial irański"),
    YER("rial jemeński"),
    QAR("rial katarski"),
    OMR("rial omański"),
    SAR("rial saudyjski"),
    KHR("riel (Kambodża)"),
    BYN("rubel białoruski"),
    LKR("rupia lankijska"),
    MVR("rupia (Malediwy)"),
    MUR("rupia Mauritiusu"),
    NPR("rupia nepalska"),
    PKR("rupia pakistańska"),
    SCR("rupia seszelska"),
    PEN("sol (Peru)"),
    KGS("som (Kirgistan)"),
    TJS("somoni (Tadżykistan)"),
    UZS("sum (Uzbekistan)"),
    KES("szyling kenijski"),
    SOS("szyling somalijski"),
    TZS("szyling tanzański"),
    UGX("szyling ugandyjski"),
    BDT("taka (Bangladesz)"),
    WST("tala (Samoa)"),
    KZT("tenge (Kazachstan)"),
    MNT("tugrik (Mongolia)"),
    VUV("vatu (Vanuatu)");

    private String currencyName;

    private CurrencyTypeInTableB(String currencyName) {
        this.currencyName = currencyName;
    }

    public String getCurrencyType() {
        return currencyName;
    }

    public static CurrencyTypeInTableB fromValue(String s) {
        for (CurrencyTypeInTableB type : values()) {
            if (type.getCurrencyType().equals(s)) {
                return type;
            }
        }
        return null;
    }
}
