package pl.nbp.model;

import java.util.SplittableRandom;

/**
 * @author kelthuzad
 * All name currency
 */
public enum CurrencyType {
    AED("dirham ZEA (Zjednoczone Emiraty Arabskie)"),
    AFN("afgani (Afganistan)"),
    ALL("lek (Albania)"),
    AMD("dram (Armenia)"),
    ANG("gulden Antyli Holenderskich"),
    AOA("kwanza (Angola)"),
    ARS("peso argentyńskie"),
    AUD("dolar australijski"),
    AWG("florin arubański"),
    AZN("manat azerbejdżański"),
    BAM("wymienialna marka (Bośnia i Hercegowina)"),
    BDT("taka (Bangladesz)"),
    BGN("lew (Bułgaria)"),
    BHD("dinar bahrajski"),
    BIF("frank burundyjski"),
    BND("dolar brunejski"),
    BOB("boliwiano (Boliwia)"),
    BRL("real (Brazylia)"),
    BSD("dolar bahamski"),
    BWP("pula (Botswana)"),
    BYN("rubel białoruski"),
    BZD("dolar belizeński"),
    CAD("dolar kanadyjski"),
    CDF("frank kongijski (Dem. Republika Konga)"),
    CHF("frank szwajcarski"),
    CLP("peso chilijskie"),
    CNY("yuan renminbi (Chiny)"),
    COP("peso kolumbijskie"),
    BBD("dolar barbadoski"),
    ETB("birr etiopski"),
    EUR("euro"),
    FJD("dolar Fidżi"),
    GBP("funt szterling"),
    GEL("lari (Gruzja)"),
    GHS("Ghana cedi"),
    GIP("funt gibraltarski"),
    GMD("dalasi (Gambia)"),
    GNF("frank gwinejski"),
    GTQ("quetzal (Gwatemala"),
    GYD("dolar gujański"),
    CRC("colon kostarykański"),
    CUP("peso kubańskie"),
    CVE("escudo Republiki Zielonego Przylądka"),
    CZK("korona czeska"),
    DJF("frank Dżibuti"),
    DKK("korona duńska"),
    DOP("peso dominikańskie"),
    DZD("dinar algierski"),
    EGP("funt egipski"),
    ERN("nakfa (Erytrea)"),
    HKD("dolar Hongkongu"),
    HNL("lempira (Honduras)"),
    HRK("kuna (Chorwacja)"),
    HTG("gourde (Haiti)"),
    HUF("forint (Węgry)"),
    IDR("rupia indonezyjska"),
    ILS("nowy izraelski szekel"),
    INR("rupia indyjska"),
    IQD("dinar iracki"),
    IRR("rial irański"),
    ISK("korona islandzka"),
    JMD("dolar jamajski"),
    JOD("dinar jordański"),
    JPY("jen (Japonia)"),
    KES("szyling kenijski"),
    KGS("som (Kirgistan)"),
    KHR("riel (Kambodża)"),
    KMF("frank Komorów"),
    KRW("won południowokoreański"),
    KWD("dinar kuwejcki"),
    KZT("tenge (Kazachstan)"),
    LAK("kip (Laos)"),
    LBP("funt libański"),
    LKR("rupia lankijska"),
    LRD("dolar liberyjski"),
    LSL("loti (Lesotho)"),
    LYD("dinar libijski"),
    MAD("dirham marokański"),
    MDL("lej Mołdawii"),
    MGA("ariary (Madagaskar)"),
    MKD("denar (Macedonia)"),
    MMK("kyat (Myanmar, Birma)"),
    MNT("tugrik (Mongolia)"),
    MOP("pataca (Makau)"),
    MUR("rupia Mauritiusu"),
    MVR("rupia (Malediwy)"),
    MWK("kwacha malawijska"),
    MXN("peso meksykańskie"),
    MYR("ringgit (Malezja)"),
    MZN("metical (Mozambik)"),
    NAD("dolar namibijski"),
    NGN("naira (Nigeria)"),
    NIO("cordoba oro (Nikaragua)"),
    NOK("korona norweska"),
    NPR("rupia nepalska"),
    NZD("dolar nowozelandzki"),
    OMR("rial omański"),
    PAB("balboa (Panama)"),
    PEN("sol (Peru)"),
    PGK("kina (Papua-Nowa Gwinea)"),
    PHP("peso filipińskie"),
    PKR("rupia pakistańska"),
    PYG("guarani (Paragwaj)"),
    QAR("rial katarski"),
    RON("lej rumuński"),
    RSD("dinar serbski"),
    RUB("rubel rosyjski"),
    RWF("frank rwandyjski"),
    SAR("rial saudyjski"),
    SBD("dolar Wysp Salomona"),
    SCR("rupia seszelska"),
    SDG("funt sudański"),
    SEK("korona szwedzka"),
    SGD("dolar singapurski"),
    SHP("Ascension Island"),
    SLL("leone (Sierra Leone)"),
    SOS("szyling somalijski"),
    SRD("dolar surinamski"),
    SSP("funt południowosudański"),
    SYP("funt syryjski"),
    SZL("lilangeni (Suazi)"),
    THB("Tajlandia"),
    TJS("somoni (Tadżykistan)"),
    TMT("nowy manat (Turkmenistan)"),
    TND("dinar tunezyjski"),
    TOP("pa'anga (Tonga)"),
    TRY("lira turecka"),
    TTD("dolar Trynidadu i Tobago"),
    TWD("nowy dolar tajwański"),
    TZS("szyling tanzański"),
    UAH("hrywna (Ukraina)"),
    UGX("szyling ugandyjski"),
    USD("dolar amerykański"),
    UYU("peso urugwajskie"),
    UZS("sum (Uzbekistan)"),
    VEF("bolivar (Wenezuela)"),
    VND("dong (Wietnam)"),
    VUV("vatu (Vanuatu)"),
    WST("tala (Samoa)"),
    XAF("frank CFA BEAC"),
    XCD("dolar wschodniokaraibski"),
    XDR("SDR (MFW)"),
    XOF("frank CFA BCEAO"),
    XPF("frank CFP"),
    YER("rial jemeński"),
    ZAR("rand (Republika Południowej Afryki)"),
    ZMW("kwacha zambijska"),
    SVC("colon salwadorski"),
    STN("dobra (Wyspy Świetego Tomasza i Książęca)"),
    MRU("ouguiya (Mauretania)");

    private String currencyName;

    private CurrencyType(String currencyName) {
        this.currencyName = currencyName;
    }

    public String getCurrencyType() {
        return currencyName;
    }

    public static CurrencyType fromValue(String s) {
        for (CurrencyType type : values()) {
            if (type.getCurrencyType().equals(s)) {
                return type;
            }
        }
        return null;
    }
}
